### ISSUE TITLE
🛑 BLOCKED 🛑  Archive older versions to external static sites

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#1173]
We should archive older versions of our docs, into separate static sites.

## Why?

Each time we add a new version to our docs, it impacts our build time -- it's a bunch more files that docusaurus needs to turn into pages. The recommendation from docusaurus, and what their docs do, is to archive old versions to separate static sites. You can see this in their version selector, which contains a section of "archived versions": 

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/1627089/185242936-6a37dc55-bd8d-4f2e-8ef2-eb6aca47c929.png">

## Implementation considerations

* We should call older versions something other than "archived" in our UI.
   * Decision: we shall call them "unsupported."
* We support releases for 18 months, so anything older than that is fair game for archiving. 
* Do we want to build old versions from source files, in case we need to update in the case of security exploits or other important reasons?
   * Decision: we will build them from source, with each unsupported version in its own branch, fully isolated from the other versions.
* If we keep the source, can we leave them in the repo but have docusaurus not build them for every build?
   * See above decision.
* Docusaurus does not hang on to old source, they remove it. They rely on the fact that [Netlify creates immutable unique URLs for every build, and they capture a URL for older versions](https://docusaurus.io/docs/versioning#keep-the-number-of-versions-small).

## Progress

```[tasklist]
### Tasks
- [x] https://github.com/camunda/camunda-platform-docs/pull/2128
- [x] https://github.com/camunda/camunda-platform-docs/pull/2129
- [x] https://github.com/camunda/camunda-platform-docs/pull/2155
- [x] https://github.com/camunda/camunda-platform-docs/pull/2160
- [x] https://github.com/camunda/camunda-platform-docs/pull/2181
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2183
- [ ] #2223
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2184
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2185
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2186
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2188
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2189
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2475
```

**Comment by akeller** [comment]
This will likely get promoted to a Product Hub Epic.

**Comment by akeller** [comment]
Before I move this to an epic, I'd like to get this question answered:

> We should look at docusaurus to see what they do with their archived versions. I know they aren't in the same repo...but maybe they are in their own repo somewhere?

I'll also socialize the "archived" language with legal and the C8 Stakeholder meeting.

**Comment by pepopowitz** [comment]
I updated the PR body, but re: docusaurus and how they handle archived sites, [they explain it here](https://docusaurus.io/docs/versioning#keep-the-number-of-versions-small). They don't hang on to the old source -- they capture the immutable URL from that specific release of the docs, and put that in the nav bar.

**Comment by pepopowitz** [comment]
What that means for us is....we can't look at docusaurus as a model for this. As far as I'm aware we don't have an immutable URL for every deployment. If we need to be able to update old versions, we'll need to come up with our own model for preserving old source, removing it from the current build, and being able to regenerate the old version docs.

**Comment by akeller** [comment]
We got a thumbs up from the C8 Stakeholder attendees this morning, but we'll need to do two things:

* Determine supported versions (we support 1.3 and 8.0, but moving forward we will support versions for 18 months)
* Decide on terminology ("Archive" wouldn't work for us)

Three things if you want to count "scheduling" this work, which is more of a question for you @pepopowitz. When would you like to consider this work?

**Comment by akeller** [comment]
Given the 30-45 min build times we saw getting the release out for 8.1/3.9.0, this will be critical by Q1. It's annoying now. I'll move this into an epic for future planning.

**Comment by akeller** [comment]
Please continue conversation on https://github.com/camunda/product-hub/issues/499.

**Comment by pepopowitz** [comment]
@akeller I'm reopening this, and attaching it as a line item for the product-hub issue. The product-hub issue became more broad, but this is still a specific tactical change we will want to prioritize & consider making.

**Comment by pepopowitz** [comment]
I'm closing this issue. There is one blocked version remaining, but it is tracked on its own. For all intents and purposes, this epic is complete.
