### ISSUE TITLE
epic: There is too much friction in submitting contributions to this project, and some of it could be automated away

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#1742]
As discussed in our most recent DX team meeting, there are several sources of friction when contributing to this project. At least a portion of the friction could be automated, or at least simplified. For those of us close to the project, there are manual workarounds and extra steps we're taking. On the other hand, people on the periphery of the project, or the occasional drop-by contributor, are set up for failure because there are too many little details to know about on each PR.

Examples of friction:

1. #1104 
2. #1396 (though this affects the core maintainers more than other contributors, because we just let the sidebars drift)
3. Changes usually need to be synchronized across multiple versions (vNext & vCurrent).
4. If they don't need to be synchronized across versions, the author has to know enough about docusaurus & versioning to know that's the case.
5. Specific reviewers need to be assigned for specific types of PRs.
6. Timing and broader scope needs to be specified so we know the urgency of our reviews & merges.

We've attempted to resolve the friction of numbers 3-6 by adding a PR template that includes several free-form questions, and a checklist. I don't think this has been as effective as we hoped. 

I consider this issue an "epic", to organize all the different bits of friction we might improve in the contribution process. In the list above, items 1 and 2 already have their own issues. Items 3-6 should eventually become their own issues, but for right now I just want to define some ways I think we can automate/improve them.

### Version synchronization

The only way we currently _catch_ this is through human interaction. The only way we currently _fix_ this is through human intervention.

#### "Business rules"
- when vCurrent is edited, vNext should likely also be edited (for future versions)
- when vNext is edited, vCurrent might also require editing (can be a case of editing what's in `/docs` without realizing that's vNext instead of vCurrent)
- when an older version is edited, I don't think we should try to predict what to do with vNext/vCurrent
- those same rules apply to both the "docs" instance and the "optimize" instance

#### Some possible improvements

- Automate catching it: if vCurrent is edited but vNext is not, or vice versa, a bot could post a comment that "you edited vWhatever, but probably also meant to edit vOther." This would eliminate the need for human interaction in 90+% of cases. Tracked at #1778.
- Automate fixing it: It is possible to use git commands to (a) generate a diff between this PR and `main`, and then (b) apply that diff to another subfolder. We could add scripts to the package.json to do this for us. There would still be human action required to run the scripts & push back to the PR, but the changes themselves would be automated. Tracked at #1779.
   - I'm likely to include these scripts in the project soon regardless, as I've been building them up as I need to synchronize content. Coming soon!
   - This does run the risk of completely borking the target version, as the patch may be based on different content than where it's applied.
   - We could leave it up to human review to ensure the version sync worked, or we could block the script from running if the affected files were different in the source than the target.
- Automate catching it _and_ automate suggestions to fix it: I _think_ we could use [this reviewdog action](https://github.com/reviewdog/action-suggester) to suggest changes from a diff in a PR review. Tracked in #1780. 
   - We definitely need to investigate further, but I think we could do something like:
      - confirm that starting target version files matched destination version files, and bail if they were out of sync before this PR
      - generate a diff between this PR & main
      - give that diff to reviewdog to post as suggestions in a review
      - There would still be human review involved, to apply all the suggestions, and to confirm they were all applied correctly. 
      - If reviewdog doesn't work for this, or suggestions are not what we want, we could also look at writing a bot that takes commands to apply the above-mentioned patching scripts, as @jwulf suggested.
- I don't think we should automate applying a patch to another version without some level of human intervention.
   - In all cases, we should treat this as _suggestions_ instead of a requirement. There will always be edge cases where changes are intentionally applied to one version but not another.

### Specific reviewers need to be assigned for specific types of PRs

We use the PR template to prompt authors to tag @christinaausley and @akeller for review, but this doesn't always happen.

@christinaausley has requested that she is still mentioned in the PR template, so that people tag her on reviews, and she knows what's happening.

#### A possible improvement

- should we use a GitHub action to auto-assign to Christina/Amara when a _content_ folder/file is edited, and Steve/Amara when an infrastructure folder/file is edited? Tracked in #1781.
   - I think we could define this as simply as "docs"/"versioned_docs"/"optimize"/"optimize_versioned_docs" are content, and everything else is infrastructure
   - if we wanted, we could also consider .htaccess and sidebars files as content, and auto-tag Christina on those.

```[tasklist]
## Tasks included in this epic
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1876
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1778
- [ ] #1104 
```

```[tasklist]
### Tasks not included in this epic, but related in the "theme" of contributor experience improvements
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1779
- [ ] #1396
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1904
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1780
- [ ] https://github.com/camunda/camunda-platform-docs/issues/1781

```

**Comment by akeller** [comment]
I like the "automate catching it" approach, but even with the CLA-bot, I have to prompt first time contributors multiple times to sign it, sometimes without ever hearing from them (ever again.... very ominous). If the automated catch prompts users to think about where their updates need to be even half the time, I would consider this a win.

If you want to split these out and scope/size them, I would see that as the next step so we can have them on our board to prioritize.

**Comment by pepopowitz** [comment]
> I like the "automate catching it" approach, but even with the CLA-bot, I have to prompt first time contributors multiple times to sign it, sometimes without ever hearing from them (ever again.... very ominous). If the automated catch prompts users to think about where their updates need to be even half the time, I would consider this a win.

Yeah, TBH I think of this one as basically an automation to _replace you specifically_, as the person who is always noticing when a PR doesn't touch all the right versions. (Or at least, that particular function of you 😅 ) Basically, it would prevent me from happy-merging something without giving thought to which versions are touched, and then having to open a follow-up PR after you point out the missed versions.

**Comment by akeller** [comment]
Amara-bot. 

Or first iteration -> Nag-bot.

**Comment by pepopowitz** [comment]
Closing, as all currently-interesting work has been completed, and other work has been extracted.
