### ISSUE TITLE
Detect missing versions in PR changes

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#1778]
Part of #1742 

Currently it is left up to humans to notice when a PR's changes affect one version of the docs but should likely be synchronized to another version. This results in PRs merging prematurely, and requiring follow-up PRs when someone notices that it should be synchronized to another version.

We should write a GitHub action that looks at the files changed, and based on the rules below, comments on the PR if changes are likely to need synchronization.

Note that the comment should be worded as a *suggestion* -- there will always be cases where a change is intended in only one version, and we should still allow for those changes to happen. 

## Version synchronization suggestion rules

Iteration 1: 

- if vCurrent is affected, but vNext is not, suggest that the changes should also be applied to vNext
- if vNext is affected, but vCurrent is not, suggest that the changes should also be applied to vCurrent
- these rules apply to both the "docs" instance and the "optimize" instance

Iteration 2:

Per https://github.com/camunda/camunda-docs/pull/2922#issuecomment-1820839017, the following rules would also be meaningful:

- if vPrevious (or older) is affected, but vPrevious+1 through vNext are not, suggest that the changes should also be applied to vPrevious+1 though vNext.

## Implementation

```[tasklist]
### Implementation
- [ ] #2922
- [ ] #3091
- [ ] https://github.com/camunda/camunda-docs/pull/3116
- [ ] https://github.com/camunda/camunda-docs/pull/3402
```

## Tasks extracted from this one

- [ ] https://github.com/camunda/camunda-docs/issues/4765

**Comment by pepopowitz** [comment]
Status: Currently collecting feedback of a prototype at https://github.com/camunda/camunda-docs/pull/2922.

**Comment by pepopowitz** [comment]
Status: First implementation is up at #3091. I'll let it sit over the holidays, and hope to merge it prior to our release in January.

**Comment by pepopowitz** [comment]
I've extracted the remaining work on this one, so that I can mark this done.
