### ISSUE TITLE
Archive v1.3/v3.7.0

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#2189]
This work can proceed as planned with the minor release in October - https://github.com/camunda/camunda-docs/issues/2189#issuecomment-2299647095

---

Archive version 1.3.

## Progress

```[tasklist]
### Previous tasks
- [ ] #2477 
- [ ] #2480
- [ ] #2494
- [ ] #2500 
- [x] Isolation step 4: [publish 1.3.20 release](https://github.com/camunda/camunda-platform-docs/releases/tag/1.3.20)
```
```[tasklist]
### Tasks that must wait until https://github.com/camunda/product-hub/issues/997 is complete
- [ ] #4474 
- [ ] https://github.com/camunda/camunda-docs/pull/4483
- [ ] #4485
- [ ] #4512 
- [x] publish new 1.3 release (https://github.com/camunda/camunda-docs/releases/tag/1.3.22)
- [ ] #4475
- [ ] #4479
```

**Comment by akeller** [comment]
This remains blocked see https://camunda.slack.com/archives/C02AWA0RF8A/p1710317097178729?thread_ts=1703089659.451659&cid=C02AWA0RF8A

**Comment by akeller** [comment]
Optimize specific OpenSearch issue - https://github.com/camunda/issues/issues/393

**Comment by akeller** [comment]
No longer blocked, ya? Shipping with the October Minor 🚀

**Comment by pepopowitz** [comment]
> No longer blocked, ya? Shipping with the October Minor 🚀

Was there an announcement somewhere? How can you tell? Everything I look at in the issues you linked above suggests there is still a long ways to go.

**Comment by akeller** [comment]
https://camunda.slack.com/archives/C070H8AE2BZ/p1723479767179909

> We proceed with archiving the 3.7 docs from the C8 docs as planned for the October release. The docs are still accessible beyond this date, but will be marked as belonging to a deprecated version

**Comment by pepopowitz** [comment]
I don't know that I want to remove the BLOCKED until we have seen it ship.

**Comment by akeller** [comment]
@pepopowitz I updated the description, but left the BLOCKED status and title.

**Comment by akeller** [comment]
This can continue to proceed as planned - https://camunda.slack.com/archives/C070H8AE2BZ/p1724946689758439?thread_ts=1723479767.179909&cid=C070H8AE2BZ
