### ISSUE TITLE
Document "Resource Deletion" in Operate user guide

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-docs#2507]
### Description

In 8.3.0 Operate will support deleting resources. This feature needs to be documented accordingly.

### Related Operate issues

https://github.com/camunda/operate/issues/3971
https://github.com/camunda/operate/issues/3972

### TODO

* [x] Add a new section "Delete Resources" in Operate -> User Guides
* [x] Add a step-by-step guide with explanations and screenshots to document the feature
* [x] Update [this](https://github.com/camunda/camunda-platform-docs/blob/main/docs/components/concepts/resource-deletion.md?plain=1#L19) url to the new page
* [ ] https://github.com/camunda/operate/issues/4170

**Comment by remcowesterhoud** [comment]
Fyi, I've added a task to update [this](https://github.com/camunda/camunda-platform-docs/blob/main/docs/components/concepts/resource-deletion.md?plain=1#L19) url to the new page. Now it links to the generic Operate page which isn't very helpful.
