### ISSUE TITLE
Update the FEEL documentation for version 8.3

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-docs#2650]
## Description 

Camunda 8.3 includes a new version of the FEEL-Scala engine [1.17.0](https://github.com/camunda/feel-scala/releases/tag/1.17.0). 

```[tasklist]
### Tasks
- [x] Update the FEEL docs
- [x] Mention the new error handling and the impact on incidents in the update guide
- [x] Mention the change of the `is defined()` function in the update guide
- [x] Update incident docs
```
