### ISSUE TITLE
Document how to setup multi-tenancy in Zeebe

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#2700]
### Description

Describe the configuration steps needed to enable multi-tenancy in Zeebe.

### AC
- [x] The gateway config flag is documented ([see link](https://github.com/camunda/camunda-docs/issues/2561#issuecomment-1717173328))
- [x] Existing users are assigned to the `<default>` tenant in Identity ([see link](https://github.com/camunda/camunda-docs/issues/2561#issuecomment-1742641043))
- [x] Migration tips are documented ([see link](https://github.com/camunda/camunda-docs/issues/2561#issuecomment-1748869177))

**Comment by koevskinikola** [comment]
#2734 resolves this issue.
