### ISSUE TITLE
Ensure screenshots use uniform naming conventions across components

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2815]
Identity screenshots include user "Bark Barkins." This should be aligned with our other screenshots and test/demo users.

Additional note: I thought we had documentation on what to include or not include in screenshots, but I can't find it on [this page](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#screenshot-automation). FYI @christinaausley 

(Edit by Christina below)

Need to:

```[tasklist]
### Tasks
- [x] Determine demo user name for screenshots.
- [x] Add to WCoE/related guidelines.
- [x] Notify teams of requested change to screenshots.
- [ ] Ensure screenshots are updated, or teams have issue in their backlog.
```

**Comment by christinaausley** [comment]
I'm going to adjust this issue to accommodate the names we use across all documentation screenshots. Even if we can't automate screenshots right now, we can at least make these more minor tweaks for consistency.

It doesn't seem like teams care much about _who_ we name the demo users/screenshots, so just need to make a decision and work with each team to ensure these are updated.

**Comment by christinaausley** [comment]
This is very similar to [this issue](https://github.com/camunda/camunda-docs/issues/2132). I'm going to close out that one, and update this one to include uniform naming across all components, regardless of the screenshot automation mechanism.

**Comment by christinaausley** [comment]
I am going to ensure usernames are "My Organization" -- I'll take a look at each of the following components and their screenshots next week:

- [ ] Guides
- [ ] Console
- [ ] Modeler
- [ ] Connectors
- [ ] Concepts
- [ ] Operate
- [ ] Tasklist
- [ ] Optimize

I did not find any instances across SM, so this will be SaaS-focused.

Of course, anyone is welcomed to create a backlog issue if we would like to incorporate a unified sandbox environment/different user personas automated in the docs screenshots. This issue solely aims to ensure all org names are the same across the screenshots to begin with.

**Comment by christinaausley** [comment]
Updating in Modeler this week, and then this can be closed out 👍
