### ISSUE TITLE
Prevent linking to double-slash URLs

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#3003]
As discussed in https://camunda.slack.com/archives/C026U8GBNSW/p1701965858544789?thread_ts=1701820206.124229&cid=C026U8GBNSW, linking to a URL like `/path/file.md/#anchor`, with a `/` between `.md` and `#`, results in a URL with a double-slash. This results in a 404 when clicking that link, and it also causes Algolia to create invalid search results (containing a double-slash in the URL). 

Ideally, these links would cause a broken build. I'm not sure why they aren't caught by the link-checking of Docusaurus or hyperlink. 

We can utilize our Vale linting rules to fail the build when links are formatted this way.

```[tasklist]
### Tasks
- [ ] #3004
- [ ] Update documentation-guidelines.md to call out `.md/#` as an incorrect practice
- [ ] Update the vale linting rules to err when this incorrect format is detected
- [ ] Correct any instances that were re-introduced before the linting was added
```

**Comment by akeller** [comment]
Option - partner with Christina on writing the docs-on-docs.

**Comment by pepopowitz** [comment]
Linting was added in https://github.com/camunda/camunda-docs/blob/e4263b3ca17883e6ea37a55933aa5f792ea442eb/styles/camunda/all/deepLinksAreFormattedCorrectly.yml.
