### ISSUE TITLE
Document support for a custom tenant-providing interceptor in Zeebe SM

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#3029]
### Description
Document support for a custom tenant-providing interceptor in Zeebe:

```[tasklist]
### Tasks
- [x] Extend the [Interceptor docs](https://docs.camunda.io/docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors/) with a section on *Implementing a tenant-providing interceptor*
- [x] Update the MultiTenancy docs for Zeebe to state that multi-tenancy in Zeebe is independent from Identity, if Zeebe is used as a standalone product
- [x] If Zeebe is used as a standalone product, and multi-tenancy is enabled, users can implement a custom tenant-providing interceptor. A link to the Interceptor docs should be provided.
- [x] If the full Camunda 8 stack is used, then a custom tenant-providing interceptor can't be used, and Identity must be configured since other Camunda 8 components must use Identity.
```

### Additional context
Related to https://github.com/camunda/zeebe/issues/14285
