### ISSUE TITLE
Create "Frontend development" section in "APIs & Tools"

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3128]
Tracked by https://github.com/camunda/camunda-docs/issues/2616

---

```[tasklist]
### Tasks
- [x] Add new section "Frontend development" in "APIs & Tools"
- [x] Update ["Working with APIs and tools" page](https://docs.camunda.io/docs/next/apis-tools/working-with-apis-tools/)
- [x] Update description of the "APIs & Tools" card on the [title page](https://docs.camunda.io/)
- [x] Create introductory page for the new section
- [x] Remove outdated reference to the GraphQL API on the "Working with APIs and tools" page
- [x] Update introductory description of the Tasklist API page
```

<img width="311" alt="image" src="https://github.com/camunda/camunda-docs/assets/56470362/b69ffa69-8542-4eb3-b526-c38edd382a1a">
