### ISSUE TITLE
Create section describing the use of the task event stream in the frontend docs

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3131]
Tracked by https://github.com/camunda/camunda-docs/issues/2616

---

```[tasklist]
### Tasks
- [ ] Add new folder "Utilize the event stream" to frontend developer docs
- [ ] Mark as "self-managed only"
- [ ] Describe how to create notifications
- [ ] Describe how to aggregate task statistics over the event stream
- [ ] Describe how to build your own source of record listening to the events
- [ ] Describe how to add own business data to the source of record using the events
```

> [!NOTE]  
> Technically, these are not frontend topics, but task application backend topics.
