### ISSUE TITLE
Create "Forms" section including pages describing how to embed form.js in own applications

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3133]
Tracked by https://github.com/camunda/camunda-docs/issues/2616

---

```[tasklist]
### Tasks
- [x] Add new section "Forms" to "Frontend development"
- [x] Describe what is form.js
- [x] Describe how to embed form.js in own applications via code
```

<img width="311" alt="image" src="https://github.com/camunda/camunda-docs/assets/56470362/b69ffa69-8542-4eb3-b526-c38edd382a1a">

**Comment by marcosgvieira** [comment]
@christian-konrad was this delivered on 8.4 or should we update the labels?
