### ISSUE TITLE
Update user task journey to Zeebe user tasks

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda-docs#3297]
## Description

The documentation reflects the user task management in Zeebe and uses this as the recommended approach, still pointing to the job-based user tasks as an alternative (for now). The respective sections outline the migration path from jobs to Zeebe user tasks. The user task forms section visibly highlights the changes for Zeebe user tasks, only supporting linked Camunda forms (via `formId` as before) and custom forms (now via an explicit new attribute).

## Tasks

* [x] ~The user tasks are described as a concept under https://docs.camunda.io/docs/next/components/concepts~ - _Not needed as the modeling page is elaborate enough_
* [x] The [user task modeling](https://docs.camunda.io/docs/next/components/modeler/bpmn/user-tasks/#user-task-forms) is adjusted to reflect Zeebe user tasks, e.g. in forms support, task headers, etc.
* [x] The [user task journey](https://docs.camunda.io/docs/next/guides/orchestrate-human-tasks/) is updated to the Zeebe user tasks instead of job-based user tasks.
* [x] ~The user [task management considerations](https://docs.camunda.io/docs/next/components/best-practices/architecture/understanding-human-tasks-management/) are updated to reflect Zeebe user tasks~ - _Looking at the page, it's generic enough and doesn't have to be adjusted_

## Out of scope

* Documenting Zeebe REST API endpoints (will come with https://github.com/camunda/zeebe/issues/15622)
* Adjusting Tasklist/Operate/Optimize details (will be provided by the individual components)
* Update guide (will be provided by individual component issues, if required)

## Additional context

* Product hub epic: https://github.com/camunda/product-hub/issues/1823

**Comment by akeller** [comment]
@christinaausley something to keep an eye on 🙂

**Comment by christian-konrad** [comment]
@tmetzke do you like to write it?
I can support, we can split work, or I review things :)

**Comment by tmetzke** [comment]
@christian-konrad, I added the first increment with #3364.
I decided against adding an entry in the concepts. The BPMN part is already quite elaborate and should be sufficient. I don't think there is more to it in general.
I'll tackle the [user task journey](https://docs.camunda.io/docs/next/guides/orchestrate-human-tasks/) and [management considerations](https://docs.camunda.io/docs/next/components/best-practices/architecture/understanding-human-tasks-management/) next.
If I'm not mistaken, you're working on a migration document with implications for existing users, right? Will that be a blog or a dedicated page in the docs? Could be beneficial to link to it from any (or multiple) of the "happy path" docs pages in an info box, at least for 8.5 (and maybe also 8.6).

**Comment by tmetzke** [comment]
This is what it looks like now (for easier comparison with the currently released version)

![image](https://github.com/camunda/camunda-docs/assets/586643/242c139a-bcf9-4432-8de7-06b9ebf1e737)
![image](https://github.com/camunda/camunda-docs/assets/586643/392bbbbd-c7f7-4af2-be4a-9bcc8519d315)
![image](https://github.com/camunda/camunda-docs/assets/586643/bf7ea498-3593-498f-b9ab-37d9f9594d50)
![image](https://github.com/camunda/camunda-docs/assets/586643/c2c9ab37-f83c-448a-be0b-f8d89dc31995)
![image](https://github.com/camunda/camunda-docs/assets/586643/6bef3cdf-a781-4969-81c4-d31da30a8278)

**Comment by christian-konrad** [comment]
> Will that be a blog or a dedicated page in the docs? 
@tmetzke both. 

I created an epic to track all the enablement material we should create: https://github.com/camunda/product-hub/issues/2124

**Comment by tmetzke** [comment]
@christian-konrad, I adjusted the text in the [user task journey](https://docs.camunda.io/docs/next/guides/orchestrate-human-tasks/). I have no idea how we usually create the other resources in there (e.g. images and the interactive guides). Can you take that over?

Regarding the [task management considerations](https://docs.camunda.io/docs/next/components/best-practices/architecture/understanding-human-tasks-management/), the descriptions are nicely generic and don't have to be adjusted, as far as I can tell. The only thing we could adjust is the link to the "claim task" Tasklist API. That API won't be usable for Zeebe user tasks, right?

**Comment by christian-konrad** [comment]
@tmetzke The interactive demo and images don't need to be updated since new users should get the Zeebe user task implementation by default, and should not care about it. The images and demo do not show any details of the properties panel, so all good
