### ISSUE TITLE
Improve Support Environments page to be more inclusive of ALL platforms & deployments

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3306]
Improve [C8 Supported Environments page](https://docs.camunda.io/docs/next/reference/supported-environments/) like following:
* **The page should include / or at least clearly link all our requirements**. The idea is that this page is the central entry point to discover all the must-requirements to run Camunda 8 fully supported
* Examples that are missing / hard to discover:
  * OpenShift support is not discoverable on the central page but only on a subpage: https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/platforms/redhat-openshift/
  * Volume performance requirements for different environments are only discoverable via the subpages. Example: https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/platforms/microsoft-aks/#volume-performance

This information should be presented as the minimum requirements to run Self Managed.

From internal thread - https://camunda.slack.com/archives/C06HE33GX9R/p1707472795152039
```[tasklist]
### Tasks
- [x] Rework form-js info
- [x] Remove older, unsupported versions of Zeebe from matrix
- [x] List and directly link to supported Kubernetes platforms
- [ ] Identify content to move to reusable components
- [ ] https://github.com/camunda/camunda-docs/issues/3369
- [ ] https://github.com/camunda/camunda-docs/issues/3370
- [ ] https://github.com/camunda/developer-experience/issues/264
```

**Comment by akeller** [comment]
Open questions:

* OpenShift gaps
  * Starting config recommendations?
  * Volume performance info?
* Are the volume performance docs the minimum requirements? Average requirements? Can we say more about how smaller or larger workloads may change these values? 
  * Basically, is 4 nodes the minimum or average? Is the instance type the minimum?
* Does Docker have any image/hardware requirements? Minimum/average requirements?
* Does Manual installation have any image/hardware requirements? Minimum/average requirements?
* Why don’t PostgreSQL supported versions match for Identity and Web Modeler? Aurora is missing from Identity, but what versions are supported?

**Comment by akeller** [comment]
Following up with Identity on Aurora missing from the Supported environments page - https://camunda.slack.com/archives/CRQAL5A1M/p1707846527383299

**Comment by akeller** [comment]
Blocked - pending feedback on overall messaging
