### ISSUE TITLE
Document how to monitor operation status in Operate user guide

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-docs#3654]
### Description

It will be possible in the Operate UI to see operation status for each process instance that is related to an operation. This needs to be documented in the Operate user guide.

### TODO

- [x] add new section to [Operate user guide](https://docs.camunda.io/docs/next/components/operate/operate-introduction/): "Monitor operation status"
- [x] add instructions with screenshots to that section guiding the user through the user story described in the [issue](https://github.com/camunda/operate/issues/6356) 
- [x] replace section [Monitor the migration progress ](https://docs.camunda.io/docs/next/components/operate/userguide/process-instance-migration/#monitor-the-migration-progress) by a link to "Monitor operation status" section
- [x] add a link to "Monitor operation status" section to [Selections and operations](https://docs.camunda.io/docs/next/components/operate/userguide/selections-operations/)

### Related issues
- https://github.com/camunda/operate/issues/6356

**Comment by akeller** [comment]
Should this be on the Operate project board? Or is this something you'll need assistance from DevEx to complete?

**Comment by pedesen** [comment]
@akeller Forgot to add it to the Operate board. :sweat_smile: done now!

**Comment by akeller** [comment]
This is labeled alpha1 - was this work completed or do the labels need to be adjusted?

**Comment by ThorbenLindhauer** [comment]
@akeller this was outdated. We have removed the label. It is in @pedesen's backlog to work on. Docs extent: We expect that we are creating a new subsection in the [Operate user guide part](https://docs.camunda.io/docs/components/operate/userguide/basic-operate-navigation/) that focuses on batch operation monitoring.
