### ISSUE TITLE
Clearly describe URL schema for both self-managed and SaaS environments, across all REST APIs.

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#3715]
Part of https://github.com/camunda/camunda-docs/issues/3649.

See also #3698 for more suggestions and details.

```[tasklist]
### Tasks
- [ ] #3698 
- [ ] Clearly describe URL schema for Administration API
- [ ] Clearly describe URL schema for Optimize API
- [ ] Clearly describe URL schema for Modeler API
```

**Comment by pepopowitz** [comment]
I believe this to be resolved by #4117.
