### ISSUE TITLE
[EPIC]: Document changes related with Camunda Exporter

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-docs#3966]
Since we're replacing Operate/Tasklist importer with Zeebe exporter, we need to adjust many pieces of documentation:

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-docs/issues/4491
- [ ] https://github.com/camunda/camunda-docs/issues/4498
- [ ] https://github.com/camunda/camunda-docs/issues/4493
- [ ] https://github.com/camunda/camunda-docs/issues/4717
- [x] Document the general sequence and details in the update guides. FEX Clean up Backlog, details of sequence and blocked exporting, etc. https://github.com/camunda/camunda-docs/pull/5023
- [ ] https://github.com/camunda/camunda/issues/24480
```

**Comment by akeller** [comment]
@sdorokhova will the Operate team handle these changes themselves? Or are you looking for support from DevEx as well? 

@conceptualshark is our new tech writer focused on the Self-Managed section and can assist.

**Comment by sdorokhova** [comment]
Hi @akeller , I think we will start with content ourselves, but will appreciate help in reviewing and reformulating more user friendly 🙏 
We will work on these docs closer to 8.6 release, probably in August.

**Comment by RomanJRW** [comment]
Closing as all subtasks are now complete
