### ISSUE TITLE
Update the Spring developer guide to include the new installation of Self-Managed

### ISSUE THREAD

**Issue by camundom** [camunda/camunda-docs#4300]
**Description**

Update the "Get Started as a Java Developer using Spring" guide to align with the new method of installing Self-managed locally with the upcoming release of Camunda 8 Desktop Modeler and C8 Run. This would include revising the Prerequisites section, removing redundant steps now covered by the new Self-managed setup, and improving the clarity and structure of the getting started steps.

```[tasklist]
### To-do
- [ ] Include links to the OpenJDK distribution for easy access.
- [ ] Include links to download the Desktop Modeler & C8 Server
- [ ] Add a helpful tip that informs the user to look for the download links in their email if they have already taken the survey.
- [ ] Discard Step 1: Install Camunda 8 Self-managed as it’s now redundant with the introduction of C8 Run
- [ ] Update to mention the latest Maven version
- [ ] Improve discoverability of the Properties panel and readability
- [ ] Add a FEEL link to the documentation 
```

**Comment by akeller** [comment]
@conceptualshark are you aligned with @camundom?
